/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author iara9
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menuContainer = new javax.swing.JPanel();
        homepageContainer = new javax.swing.JPanel();
        jTabbedPane_listagemContainer = new javax.swing.JTabbedPane();
        jPanel_listaReceitas = new javax.swing.JPanel();
        jPanel_ListaDespesas = new javax.swing.JPanel();
        jPanel_listaLancamentos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        bg.add(menuContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        homepageContainer.setBackground(new java.awt.Color(238, 238, 238));

        jTabbedPane_listagemContainer.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane_listagemContainer.setForeground(new java.awt.Color(51, 51, 51));

        jPanel_listaReceitas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_listaReceitasLayout = new javax.swing.GroupLayout(jPanel_listaReceitas);
        jPanel_listaReceitas.setLayout(jPanel_listaReceitasLayout);
        jPanel_listaReceitasLayout.setHorizontalGroup(
            jPanel_listaReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel_listaReceitasLayout.setVerticalGroup(
            jPanel_listaReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jTabbedPane_listagemContainer.addTab("Receitas", jPanel_listaReceitas);

        jPanel_ListaDespesas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_ListaDespesasLayout = new javax.swing.GroupLayout(jPanel_ListaDespesas);
        jPanel_ListaDespesas.setLayout(jPanel_ListaDespesasLayout);
        jPanel_ListaDespesasLayout.setHorizontalGroup(
            jPanel_ListaDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel_ListaDespesasLayout.setVerticalGroup(
            jPanel_ListaDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jTabbedPane_listagemContainer.addTab("Despesas", jPanel_ListaDespesas);

        jPanel_listaLancamentos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_listaLancamentosLayout = new javax.swing.GroupLayout(jPanel_listaLancamentos);
        jPanel_listaLancamentos.setLayout(jPanel_listaLancamentosLayout);
        jPanel_listaLancamentosLayout.setHorizontalGroup(
            jPanel_listaLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel_listaLancamentosLayout.setVerticalGroup(
            jPanel_listaLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jTabbedPane_listagemContainer.addTab("Lancamentos", jPanel_listaLancamentos);

        javax.swing.GroupLayout homepageContainerLayout = new javax.swing.GroupLayout(homepageContainer);
        homepageContainer.setLayout(homepageContainerLayout);
        homepageContainerLayout.setHorizontalGroup(
            homepageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageContainerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane_listagemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        homepageContainerLayout.setVerticalGroup(
            homepageContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepageContainerLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jTabbedPane_listagemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        bg.add(homepageContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 710, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel homepageContainer;
    private javax.swing.JPanel jPanel_ListaDespesas;
    private javax.swing.JPanel jPanel_listaLancamentos;
    private javax.swing.JPanel jPanel_listaReceitas;
    private javax.swing.JTabbedPane jTabbedPane_listagemContainer;
    private javax.swing.JPanel menuContainer;
    // End of variables declaration//GEN-END:variables
}
